services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  server:
    depends_on:
      - postgres
    build:
      context: ./server
    develop:
      watch:
        # Sync the /app directory
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/.venv

        # Rebuild when pyproject.toml changes
        - action: rebuild
          path: ./backend/pyproject.toml
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - POSTGRES_HOST=postgres

volumes:
  postgres_data:
